apiVersion: v2
name: ollama-inference
description: Ollama high-throughput LLM inference engine Helm chart
type: application
version: 0.1.0
appVersion: "v0.19.0"
keywords:
  - llm
  - Ollama
  - inference
  - gpu
  - nvidia
  - ascend
  - sglang
home: https://github.com/axeprpr/helm-llm-repo
sources:
  - https://github.com/axeprpr/helm-llm-repo
maintainers:
  - name: axeprpr
    email: axe3@qq.com
