apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelBooster
metadata:
  name: tiny-gpt2
  namespace: kthena-demo
spec:
  backend:
    name: backend1
    type: vLLM
    modelURI: hf://sshleifer/tiny-gpt2
    cacheURI: hostpath://tmp/cache
    minReplicas: 1
    maxReplicas: 1
    env:
      - name: HF_ENDPOINT
        value: https://hf-mirror.com
    workers:
      - type: server
        image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
        replicas: 1
        pods: 1
        config:
          served-model-name: tiny-gpt2
          max-model-len: 2048
          max-num-batched-tokens: 4096
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
