replicaCount: 2

image:
  tag: v0.17.1-x86_64

model:
  name: Qwen/Qwen2.5-0.5B-Instruct

scheduler:
  type: volcano
  volcano:
    createPodGroup: true
    groupMinMember: 2
    queueName: default

gpuType: nvidia
runtimeClassName: nvidia

extraEnv:
  - name: http_proxy
    value: http://192.168.3.42:7890
  - name: https_proxy
    value: http://192.168.3.42:7890
  - name: HF_HUB_DISABLE_TELEMETRY
    value: "1"

resources:
  limits:
    nvidia.com/gpu: "1"
    memory: 24Gi
    cpu: "8"
  requests:
    nvidia.com/gpu: "1"
    memory: 12Gi
    cpu: "4"

engine:
  tensorParallelSize: 1
  maxModelLen: 4096
  gpuMemoryUtilization: 0.85
