apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob-sleep
  namespace: volcano-single
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: default
  maxRetry: 1
  ttlSecondsAfterFinished: 60
  tasks:
    - replicas: 1
      name: runner
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: sleeper
              image: docker.io/calico/node:v3.25.0
              command:
                - sh
                - -c
                - echo vcjob-ok && sleep 5
              resources:
                requests:
                  cpu: "1"
                  memory: "64Mi"
                limits:
                  cpu: "1"
                  memory: "64Mi"
