apiVersion: apps/v1
kind: Deployment
metadata:
  name: preempt-low
  namespace: volcano-single
spec:
  replicas: 8
  selector:
    matchLabels:
      app: preempt-low
  template:
    metadata:
      labels:
        app: preempt-low
      annotations:
        volcano.sh/preemptable: "true"
    spec:
      schedulerName: volcano
      priorityClassName: volcano-low
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.8
          resources:
            requests:
              cpu: "4"
              memory: "64Mi"
            limits:
              cpu: "4"
              memory: "64Mi"
