apiVersion: v1
kind: Service
metadata:
  name: {{ include "vision-inference.fullname" . }}
  labels:
    {{- include "vision-inference.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "vision-inference.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vision-inference.fullname" . }}-metrics
  labels:
    {{- include "vision-inference.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    {{- include "vision-inference.selectorLabels" . | nindent 4 }}
