apiVersion: v2
name: llamacpp-inference
description: llama.cpp high-throughput LLM inference engine Helm chart
type: application
version: 0.1.0
appVersion: "b8580"
keywords:
  - llm
  - llamacpp
  - inference
  - gpu
  - nvidia
  - ascend
  - sglang
home: https://github.com/axeprpr/helm-llm-repo
sources:
  - https://github.com/axeprpr/helm-llm-repo
maintainers:
  - name: axeprpr
    email: axe3@qq.com
